### ISSUE TITLE
Complete implementation of Llama and other LLMs

### ISSUE THREAD

**Issue by ZihaoTan** [ml-explore/mlx-examples#218]
The Llama implementation seems to be much simpler than the official version [meta-llama.generation.py](https://github.com/facebookresearch/llama/blob/main/llama/generation.py) with many parameters (top_p, logprobs) not functioning. Is there any consideration for reproducing a complete version or welcoming other contributors to implement it?

**Comment by awni** [comment]
The intention behind these examples is to be simple so that they 1. are educational and 2. serve as a starting point for customizations / more sophisticated techniques.

With that in mind it's a low priority for us to add all of those options. But would be really great to see a community contributed repo that does that!
