### ISSUE TITLE
[Feature Request] support for multimode model like LLaVA

### ISSUE THREAD

**Issue by iLoveBug** [ml-explore/mlx-examples#344]
Thanks for your great work guys. I am looking for an example for running LLaVA in mlx. Hope it could be included in the example repo.

Best regards,

**Comment by gboduljak** [comment]
Hi @iLoveBug :) Please see the existing issue https://github.com/ml-explore/mlx-examples/issues/207. That issue is very similar to your request. I think that having an example of multimodal model like LLaVA is very cool and I am planning to contribute to this. However, to implement many open-source multimodal models, we need to have a good implementation of CLIP (e.g. for LLaVA) and we may need to implement some layers in `mlx` core (e.g. interpolation for ferret).  I am working on the implementation of CLIP (https://github.com/ml-explore/mlx-examples/pull/315). My goal is to complete the implementation of CLIP this week (right now waiting for complete feedback) and then start the implementation of LLaVa. After LLaVA, my plan is to contribute to an implementation of [ferret](https://github.com/apple/ml-ferret).

**Comment by iLoveBug** [comment]
@gboduljak  that's so cool! looking forward your great contribution!

**Comment by awni** [comment]
I think we can close this as #461 is merged.
