### ISSUE TITLE
Issue with models fine tuned with older version of mlx_example

### ISSUE THREAD

**Issue by ivanfioravanti** [ml-explore/mlx-examples#402]
I was trying the fine tuned model from HF MLX here: https://huggingface.co/mlx-community/Mistral7B-Inst-v0.2-4bit-mlx-distilabel-capybara-dpo-7k

From instructions in the model card it seems the model used the old hf_llm that has been removed in   [commit #c6440416a265b9869c1a9ff08bf595193babb38](https://github.com/ml-explore/mlx-examples/commit/c6440416a265b9869c1a9ff08bf595193babb38c)

I tried running it with mlx 0.0.11 and 0.1.0, with latest version of mlx_examples but I get ... as output 

```
Prompt: <s>[INST] What wights more 1kg of feathers or 0.5kg of steel? [/INST]
... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...
==========

```
Does this mean we need to requantize/upload models on HF MLX Repo?

**Comment by awni** [comment]
I don't know why that model isn't working. Do you have any idea at what point it was working?

In general, you shouldn't need to re-quantize models. There are some cases where we quantize layers now that we did not before, but in those cases it should crash because the shapes will be incorrect.

**Comment by awni** [comment]
Actually, I don't really understand now, because it looks like that model was made 1 day ago... maybe the right thing to do is to [make a discussion](https://huggingface.co/mlx-community/Mistral7B-Inst-v0.2-4bit-mlx-distilabel-capybara-dpo-7k/discussions) in the model repo itself and chat with the author. It seems like this could be an issue with the model itself?

If there is some reason to believe this is an issue with mlx / mlx-examples please let me know and I will gladly reopen this.

**Comment by awni** [comment]
I made a discussion on it: https://huggingface.co/mlx-community/Mistral7B-Inst-v0.2-4bit-mlx-distilabel-capybara-dpo-7k/discussions/1
