### ISSUE TITLE
No example for generating using the adapters.npz

### ISSUE THREAD

**Issue by siddartha-10** [ml-explore/mlx-examples#485]
I think the code used for generating from the fine-tuned model using ```adapters.npz ``` is missing from the doc?
https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md#Generate

**Comment by siddartha-10** [comment]
I am assuming that we need to first fuse and upload the model and then use the hugging_face model name and then generate? So something like this
```
python3 -m mlx_lm.generate \
 --model directory/model_name \
 --max-tokens 1000 \
 --prompt "write a c program to print even numbers"
```

**Comment by mzbac** [comment]
mlx-lm.lora behave the same as the lora example, so you can use the same command to test the fine-tuned adpater as:
```
python lora.py --model <path_to_model> \
               --adapter-file <path_to_adapters.npz> \
               --max-tokens 50 \
               --prompt "table: 1-10015132-16
columns: Player, No., Nationality, Position, Years in Toronto, School/Club Team
Q: What is terrence ross' nationality
A: "
```

**Comment by siddartha-10** [comment]
Wouldn't that take the model directly from huggingface or mlx_community, rather than the model which i fine tuned on?

**Comment by awni** [comment]
You can generate from the fine-tuned model in two ways:
1. Fuse the base model with the adapters to produce a new model. Then use that model to generate as usual. [Instructions to fuse here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md#Fuse-and-Upload)
2. Generate with the base model + adapters without fusing them using the command @mzbac wrote above.

Note the 2nd option will usually give you better results than the 1st since some information is lost when you fuse the adapters into the base model, especially if the base model is quantized.

(Closing this for now as I think we answered the question, but let me know if you have any further questions / issues and we can reopen)
