### ISSUE TITLE
LoRA vs. QLoRA performance comparison

### ISSUE THREAD

**Issue by madroidmaq** [ml-explore/mlx-examples#511]
When I try both LoRA and QLoRA fine-tuning approaches using the same parameters and base model, I found that some metrics (e.g. tokens_sec, gpu, etc.) don't have a significant advantage, and how should I interpret these data. The yellow color in the figure below represents the QLoRA approach (4 bit) and the purple color represents the LoRA approach.

![image](https://github.com/ml-explore/mlx-examples/assets/6247142/c8b71048-3a4a-4033-ba27-9cb9a7ad0150)

![image](https://github.com/ml-explore/mlx-examples/assets/6247142/ba7052e1-becb-4a17-bfb6-ba149ecda85e)

**Comment by madroidmaq** [comment]
@mzbac During the inference of the model, it is indeed a bit faster with 4bit. Apart from the 0.5B small model, I also tried the 2.7B phi2 model, but basically did not see any significant advantage of QLoRA during fine-tuning.

![image](https://github.com/ml-explore/mlx-examples/assets/6247142/c976c9d0-caea-4628-ae56-4a4e4c669154)

**Comment by mzbac** [comment]
Are you referring to the fact that Qlora took a similar amount of memory as Lora? I think there is a caching issue in mlx at the moment. I believe mlx team is working on that.

**Comment by awni** [comment]
For single machine training the primary advantage of QLoRA over LoRA is that it requires a lot less memory. You will see a bigger advantage for bigger models, where the model itself accounts for most of the memory.

In fact, if you have enough RAM for regular LoRA it can be faster. The reason is that training is typically compute bound, meaning it's bound by how fast we can do basic multiplies and additions. If you use quantization then you are increasing the amount of compute in a given matrix multiplication. This means training will be slower.

So I would use QLoRA for fine-tuning very large models that use a lot of your machine's memory. But for small models regular LoRA is going to be faster and more accurate so probably the right call.

As a side note I do not rely much on the system memory use reports because I have found them to be innacurate (sometimes by large amounts). We are adding some APIs to let you query memory use in https://github.com/ml-explore/mlx/pull/761 (`mx.get_active_memory`, `mx.get_peak_memory`, etc).

**Comment by madroidmaq** [comment]
Corresponding information has been added https://github.com/ml-explore/mlx-examples/pull/528
