### ISSUE TITLE
lora on mistral error

### ISSUE THREAD

**Issue by thegodone** [ml-explore/mlx-examples#59]
I did convert the model using the mistral instructions not the lora instructions.

I move the mistral-7B-v0.1 path from mistral to lora folder and run this instructions and got the following error:

```
python lora.py --model mistral-7B-v0.1/ \                                   
               --train \
               --iters 600
Loading pretrained model
Traceback (most recent call last):
  File "/Users/ethangodin/Github/mlx-examples/lora/lora.py", line 288, in <module>
    model, tokenizer = load_model(args.model)
  File "/Users/ethangodin/Github/mlx-examples/lora/lora.py", line 270, in load_model
    model_args = ModelArgs(**config)
TypeError: __init__() got an unexpected keyword argument 'sliding_window'
```

**Comment by thegodone** [comment]
I think the documentation is not so clear on the "path" vs "filename" that could be improved : 

```
python convert.py --torch_model  mistral-7B-v0.1 --mlx_model mistral-7B-v0.1/mlx_mistral_7b.npz 
python lora.py --model mistral-7B-v0.1/mlx_mistral_7b.npz --train --iters 600 
```

**Comment by awni** [comment]
So in the LoRA documenation it says:

`python convert.py <path_to_torch_model> <path_to_mlx_model>`

The input and output paths are directories and the conversion script should make a new `params.json` in the output directory that is what the `lora.py` script expects.

 If you use the lora conversion you should be good to go, otherwise you can copy the `params.json` from the original Mistral model and remove the `sliding_window` field.
