### ISSUE TITLE
How to get a better trade-off between GPU-efficiency and memory footprint?

### ISSUE THREAD

**Issue by Ericmututu** [ml-explore/mlx-examples#594]
Thanks for releasing such wonderful work!

During my implementation,  two isssues are raised:
1. Due to the swap memory mechanism, it is difficult to determine the number of trainable parameters directly based on the GPU-memory. Based on my experimental observation, as the number of trainable parameters increases, GPU-utilization will first rise and then decline.
2. When the number of trainable parameters exceeds a certain threshold, the OOM will not display an interrupt prompt, but **directly crash the computer!!!** Can this be fixed in the future?

**Comment by awni** [comment]
> Due to the swap memory mechanism, it is difficult to determine the number of trainable parameters directly based on the GPU-memory. Based on my experimental observation, as the number of trainable parameters increases, GPU-utilization will first rise and then decline.

Yea you can set the memory limit with `relaxed = False` if you want it to crash rather than swap:

`mx.metal.set_memory_limit(10*2**30, relaxed=False)` will give you a hard threshold of 10GB. If your working set grows bigger than that, the program will crash but you're machine shouldn't crashed.


> When the number of trainable parameters exceeds a certain threshold, the OOM will not display an interrupt prompt, but directly crash the computer!!! Can this be fixed in the future?

Using too much memory can cause the machine to slow a lot, but usually doesn't cause it to crash in my experience.....but allowing swap is usually desirable so probably going to keep that as the default.

**Comment by Ericmututu** [comment]
Thank you, it helps me a lot.
