### ISSUE TITLE
Error while finetuning with LoRA: Unable to allocate 12 bytes.

### ISSUE THREAD

**Issue by shamikbose** [ml-explore/mlx-examples#70]
I tried to follow the example in the `lora` directory, but I get the following error

`libc++abi: terminating due to uncaught exception of type std::runtime_error: [malloc_or_wait] Unable to allocate 12 bytes.`

I tried to run with the default settings and only changed the `iters` value to 100

`lora % python lora.py --model mlx_model --train --iters 100`

I get the following output before I get the error above:

```
Loading pretrained model
Total parameters 7243.436M
Trainable parameters 1.704M
Loading datasets
Training
```

**Comment by awni** [comment]
32 GB might be a stretch for the Lora finetuning as it uses 32 bit precision right now. One thing you can try is changing to a lower precision (change [here](https://github.com/ml-explore/mlx-examples/blob/main/lora/lora.py#L265) to `mx.float16` or `mx.bfloat16`). I can't promise it will work because we haven't tested that yet.

We will make it an argument once we have had a chance to test it.

You can also try using a smaller batch size `--batch_size 1` should save a lot of memory, for example. But it will be slower.

**Comment by shamikbose** [comment]
@awni @ivanfioravanti I managed to get it working with `mx.float16` and batch_size=2. This is what training currently looks like
<img width="479" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/50837285/c83104b1-ecbd-4552-9a82-b29a52301947">

**Comment by awni** [comment]
Oof 4 tokens per second is slow! For context the m2 ultra is 100x faster (with batch size 4) and 32-bit precision..

It feels like you may be swapping given how slow it is. I think for the lower memory machines we need something like Q-lora / reduce memory requirements for this to not be too too slow.

**Comment by shamikbose** [comment]
Yeah, GPU usage seems to be quite low (~50%). I saw in a different issue discussion that quantization was also on the cards, so that would be generally quite helpful

**Comment by awni** [comment]
#115 can help reduce memory requirements by letting you use fewer LoRA layers.

**Comment by DamascusGit** [comment]
and where on 265 do i exactly make the change to mx.float16? I can't seem to figure that one out.

> #115 can help reduce memory requirements by letting you use fewer LoRA layers.
> 
> The README.md is also updated with some tips to reduce memory use.

**Comment by awni** [comment]
If you pull the latest it defaults to `float16`.
