### ISSUE TITLE
Please support jax metal example with 64bit float

### ISSUE THREAD

**Issue by QuantumJaeYoo** [ml-explore/mlx-examples#71]
.

**Comment by awni** [comment]
Can you be more specific with what you mean by `jax metal example`? Also why do you need double (64-bit) precision?

**Comment by QuantumJaeYoo** [comment]
I apologize, I had no time to finish the content, so I just added a dot(.)

To be more specific, I want to ask about the mnist example, I saw that both `main.py` and `torch_main.py` support metal backends, but `jax_main.py` doesn't support it. So I tried to install the jax-metal to test it on my end, and I saw that 64-bit is not supported. The reason why we need 64-bit is we are performing scientific codes requiring high-precision.

**Comment by awni** [comment]
I see, so Jax may not support 64-bit. I would file an issue with Jax about that as we do not have any ties to the Jax Metal back-end.

If you are interested in higher precision in MLX, you can file an issue to the [core repo](https://github.com/ml-explore/mlx). It's likely not a top priority for us, but may also not be that much work to have decent op coverage since most of our kernels are templated.
