### ISSUE TITLE
delete and uninstall

### ISSUE THREAD

**Issue by MikeyBeez** [ml-explore/mlx-examples#764]
How do I remove everything this installed.  It's absolute garbage. I'll stick with ollama.

**Comment by awni** [comment]
😢 

```
rm -rf mlx-examples/
```

**Comment by MikeyBeez** [comment]
That doesn't cleanup all the models that were loaded.

**Comment by awni** [comment]
https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/MANAGE.md

**Comment by MikeyBeez** [comment]
Forget it.  I'll figure it out myself.  Apple can't do any AI properly.  This is the third time I wasted time with this junk.  It would be funny if it weren't so sad.

**Comment by MikeyBeez** [comment]
rm -rf models--mistralai--Mistral-7B-Instruct-v0.2/

**Comment by AKLABZ** [comment]
It'll depend on a couple things! If you only installed the standard mlx package via pip or conda, try running `rm -rf mlx`
- 
For pip open the terninal and run:
`python -m pip uninstall mlx`
(replace `pip` with `pip3` if necessary)
- 
For conda it's pretty similar:
`conda remove mlx`
-
Be sure to remove any environments you may have created for mlx! 
-
If you installed the `mlx-lm` package from Hugging Face and used it to download models, you can remove the package the same way! `python -m pip` (or `pip3`) `uninstall mlx-lm`
-
Last thing! If you happened to use the Hugging Face package, the downloaded models default to your `.cache` directory! It's a hidden directory but you can find it two different ways:
-
Open your terminal and cd to `/Users/YourUserName/.cache/huggingface` Inside you'll find any models you may have downloaded through mlx-lm. Once you get there run `rm -rf /ModelDirectory`
-
You can also simply open the Finder app and press `cmd` + `shift` + `.` to reveal your hidden directories. You'll see the `.cache` directory pop up so you can navigate into it and delete what you don't need.
-
You should be good to go after that 🙂

**Comment by AKLABZ** [comment]
Don't know why my comment is ginormous 😅 iPhone app doesn't play well ig

**Comment by MikeyBeez** [comment]
Thank you, @AKLABZ .  When models are loaded from Huggingface there are a lot of messages.  I saw about 25GBs of models altogether.  So I was concerned.  I deleted the huggingface model directory in .cache.  Thank you, but I was concerned there might be others.  I ran sudo find / -type f -size +1M -mtime -1 2>/dev/null to look for more files and didn't see them.  And I used conda env remove -n mlx-lm to remove the environment.  I was excited to think mlx could improve the performance of my local models, but the opposite is true.  It's much much slower.  In fact it's unusable.  It takes more space and does less -- in fact it does nothing.  One token per minute on my 16GB memory M1 Mac is a joke.  Doesn't Apple test this stuff before they release it?  Why waste their users' time?    Does MLX stand for Machine Learning Excrement?   ;)

**Comment by AKLABZ** [comment]
@MikeyBeez hmm, those numbers don't seem right when looking at the crude benchmarks I've been collecting. Have you tried messing with the tokenizer arguments? And making sure you're downloading the correct model that's not only optimized for the mlx framework but one that's quantized enough to not dip into your memory swap? I'm on an M1 Pro with 32 gb of ram so my metrics are going to be a bit different, but you shouldn't be getting 1 tok/sec. 
I attached my speed benches for llama 3 8B in different quants and compared them to mistral 2.5 which is what I was using locally before llama 3 released and for fun I threw in chatgpt metrics I got from the dev console. I run the Q8 model just because I have the extra ram but the Q6 should work fine for you. Llama 3 Q8 is generating about 18-20 tok/sec on my setup and that's with no optimization other than upping the max_tokens. I plan on fine tuning it to get rid of the fluff and get it dialed in on coding assistant tasks which will up the tok speed. I have my LM studio server benchmarks somewhere, but they were pretty much the same and that's using their chat ml profile. Again, MLX with no optimizations other than increasing max_token from 100 (default) to 500 is the only optimization I've done so far.

Also, I manage my fans manually which keeps the temp down, you could be thermal throttling or ram throttling. Try disabling all login items and background tasks and reboot so you can get a baseline system ram utilization. Just gotta see where you can cut your usage down in order to properly assess performance. 16gb of total ram is barely gonna leave any wiggle room for running the model while doing tasks. Sorry this was long, just don't want you to walk away from a framework that will suit your machine best at the end of the day. MLX isn't very abstracted and obviously it's a new framework which is bound to cause problems. Keep messing around, or just stick with cloud based services until the right model for your workflow releases. 

<img width="555" alt="Screenshot 2024-05-08 at 2 04 07 PM" src="https://github.com/ml-explore/mlx-examples/assets/133277560/41b10bb5-a19c-4c0e-ba35-656075da04fe">
<img width="555" alt="Screenshot 2024-05-08 at 2 25 35 PM" src="https://github.com/ml-explore/mlx-examples/assets/133277560/a304a67d-32d6-4be5-b9bf-b5de4c988811">

**Comment by AKLABZ** [comment]
@MikeyBeez This was my prompt btw, each model provided almost identical passing code, just some slight variations in naming conventions. ![image](https://github.com/ml-explore/mlx-examples/assets/133277560/6cbc1941-17a4-4bcd-b9d5-037502aa7244)

**Comment by MikeyBeez** [comment]
@AKLABZ I think I've had enough.  I'm really grateful that you've taken so much effort to respond to me.  Nevertheless, I don't want to spend hours installing software when I have something that's serviceable that took five minutes to install.  Nor do I want to fight with Huggingface tokens, etc.  Apple has been a spectacular disappointment in the AI arena.  I feel the same way about Apple's development environment.  I haven't written in X-Code in years because it's such a pain in the behind.  I just use python and gradio.  I suspect there's something wrong at the very top -- somebody's idiot nephew is in charge or the like.  How else can one explain a premium player being so behind?  The one stellar AI feature Apple gave me is being able to copy text from video.  Otherwise, Apple's AI improvements are almost non-existent.

**Comment by agouliel** [comment]
@MikeyBeez there was an answer above (by @awni) but you choose to ignore it for some reason.
