### ISSUE TITLE
SLM Example Code

### ISSUE THREAD

**Issue by williamzebrowskI** [ml-explore/mlx-examples#768]
This is not an issue but more of a question/ask - (I don't see a discussion section in this repo)

The `transformer_lm` example looks awesome and would love to see more examples like this.  Can others examples be shared or links be provided that show tutorials in working directly with the MLX framework creating transformer models?

Thanks

**Comment by awni** [comment]
This might be a good place for you to check out: https://github.com/ml-explore/mlx/discussions/654. You can also comment there or start a discussion in MLX core to see if anyone has built something more like what you are looking for.

Also sorry discussions are not enabled here. I will turn them on so that we don't get so many non-issue issues.
