### ISSUE TITLE
Why change the module decomposition of whisper

### ISSUE THREAD

**Issue by m-a-sch** [ml-explore/mlx-examples#809]
Does MLX instead of torch really require to move away from the openAI module decomposition? Why?

**Comment by awni** [comment]
Could you explain what you mean by "module decomposition"?

**Comment by m-a-sch** [comment]
Probably not the right term. I mean this
![modules](https://github.com/ml-explore/mlx-examples/assets/37264604/00569a32-a35f-44ce-b48f-583002faf508)

**Comment by awni** [comment]
I understand your question now. Some things (e.g. triton_ops) don't make sense for MLX. Other things (e.g. torch_whipser and load_models are there to facilitate the conversion). Otherwise it's mostly the same with some simplifications. We don't intend for it to be a 1:1 match in terms of API and code organization. It should produce the same results though given the same audio.
