### ISSUE TITLE
Error loading GGUF Mixtral 8x7B Q_8 model

### ISSUE THREAD

**Issue by HaskDev0** [ml-explore/mlx-examples#842]
Hi all,

I downloaded the [mixtral-8x7b-v0.1.Q8_0.gguf](https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF/blob/main/mixtral-8x7b-v0.1.Q8_0.gguf)] model and was trying to load it for inference using mlx-examples/llms/gguf_llm/generate.py. But during the load time it trows the following error:
```
[INFO] Loading model from .../mixtral-8x7b-v0.1.Q8_0.gguf
8 bits quantized model
Model info
==========
Context length: 32768
Vocab size: 32000
Hidden size: 4096
Num layers: 32
Num attention heads: 32

Traceback (most recent call last):
  File ".../mlx-examples/llms/gguf_llm/generate.py", line 85, in <module>
    model, tokenizer = models.load(args.gguf, args.repo)
  File ".../mlx-examples/llms/gguf_llm/models.py", line 309, in load
    model.load_weights(list(weights.items()))
  File ".../ENVIRONMENTS/LargeLanguageModelsV2.Mixtral8x7B.GGUF.Q8_0/lib/python3.9/site-packages/mlx/nn/layers/base.py", line 211, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.16.mlp.up_proj.6.biases model.layers.25.mlp.down_proj.1.scales model.layers.14.mlp.up_proj.6.scales model.layers.15.mlp.up_proj.1.biases model.layers.28.mlp.down_proj.1.weight
...
```

What can be an issue here and are there any workarounds to solve the issue?

Thank you in advance.

**Comment by awni** [comment]
That example does not support Mixtral. You would need to modify it to support the Mixtral MOE. The GGUF example there is intended to be a simple example of how to use GGUF with MLX. We don't intend to update it to support lots of different models in order to keep it simple.

Instead, I would recommend using MLX LM which can run quantized Mixtrals using safetensors.

1. `pip install mlx-lm`
2. `mlx_lm.generate --model mlx-community/Mixtral-8x22B-Instruct-v0.1-4bit --prompt "hello" --max-tokens 128 --temp 0.0`
