### ISSUE TITLE
grad-checkpoint makes trained tokens increase gradually

### ISSUE THREAD

**Issue by alphrc** [ml-explore/mlx-examples#878]
After using `--grad-checkpoint`, the trained tokens increase gradually and reach the size of the whole dataset at the last iteration, while not using it would have the trained tokens in each iteration always be the same of the size of the dataset.

Why?

**Comment by awni** [comment]
I'm not understanding your question. Trained tokens should be going up in all cases because its an sum over the total number of tokens trained on so far. I don't think you should see a difference there in terms of total tokens so it's possible there is a bug.

Could you share the command you ran / output you were seeing so we can reproduce that?

**Comment by awni** [comment]
Closing as inactive. If there was an issue here please comment and we can reopen.
