### ISSUE TITLE
Backward Hooks

### ISSUE THREAD

**Issue by Aakriti23** [ml-explore/mlx-examples#987]
is there any torch equivalent of backward hook in MLX? I would like to have access to the intermediate gradients and possibly edit them during the backward pass.

**Comment by angeloskath** [comment]
Sorry for the late reply. You can implement the equivalent of a backward hook in a few lines of python as follows

```python
import mlx.core as mx


def hook(x, cb):
    @mx.custom_function
    def _inner(x):
        return x

    @_inner.vjp
    def _inner(x, dx, _):
        new_dx = cb(dx)
        return new_dx or dx

    return _inner(x)

    
def f(x):
    return 2 * hook(x.square(), print) + x + 1


mx.eval(mx.grad(f)(mx.array(0.1)))
```

The above will print `2` which is the gradient of `x**2` in the expression `2 * x**2 + x + 1`.

You can put `dx` in some outer list to evaluate later or even compute some loss and 2nd order gradients and so on and so forth.

I would advise a little bit of caution when evaluating inside a hook eg printing like above because we need to keep the whole graph in memory since we don't know what you want to do with the graph afterwards. This means that for large networks, evaluating inside a backward hook like above may really balloon your memory requirements. I suggest just putting the gradients in an external data structure and evaluating them after the call to `grad`.

If there is something you feel you can't do with the above, let us know otherwise feel free to close the issue.

**Comment by rachtibat** [comment]
Dear @angeloskath,

Thank you for this nice example. Is there also an official documentation page explaining how to define hooks?

Best greetings

**Comment by angeloskath** [comment]
The documentation for `mx.custom_function` can be found at https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.custom_function.html .

The hook above is a simple identity function with a custom gradient. Note that if you `mx.compile` the outer function then the hook will only be called once!

I will close the issue but feel free to open again if you encounter an issue. If it is a general mlx issue perhaps the [https://github.com/ml-explore/mlx](https://github.com/ml-explore/mlx) repository would be a better fit as well.
